version: '3.8'

services:
  web:
    image: jobexpo_app_image_dev
    container_name: jobexpo_app_container_dev
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        BUILD_ENV: dev
    volumes:
       - .:/backend
    environment:
      - DJANGO_ENV=dev
      - DJANGO_SETTINGS_MODULE=jobexpo_project.settings.local
    env_file: .env
    ports:
      - "8000:8000"
